[package]
name = "pagemaker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
regex = "1"
rand = { version = "0.8", features = [] }
minify-html = "0.15"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
