name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "opened", "synchronize", "reopened", "ready_for_review" ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy --all-targets

      - name: Build release
        run: cargo build

      - name: Test
        run: cargo test
